# Generated by Django 6.0.1 on 2026-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('identification', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('category', models.CharField(choices=[('INSTRUCTOR', 'Instructor'), ('ASISTENTE', 'Asistente'), ('AUXILIAR', 'Auxiliar'), ('TITULAR', 'Titular')], default='INSTRUCTOR', max_length=20, verbose_name='Categoría Docente')),
                ('scientific_degree', models.CharField(choices=[('NONE', 'Ninguno'), ('MSC', 'Máster en Ciencias'), ('DR', 'Doctor en Ciencias')], default='NONE', max_length=20, verbose_name='Grado Científico')),
                ('contract_type', models.CharField(choices=[('FULL_TIME', 'Tiempo Completo'), ('PART_TIME', 'Tiempo Parcial'), ('HOURLY', 'Por Horas')], default='FULL_TIME', max_length=20, verbose_name='Tipo de Contrato')),
                ('specialty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
