# Generated by Django 6.0.1 on 2026-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('LECTURE', 'Conferencia'), ('PRACTICAL', 'Clase Práctica'), ('SEMINAR', 'Seminario'), ('LAB', 'Laboratorio'), ('WORKSHOP', 'Taller')], default='LECTURE', max_length=20, verbose_name='Tipo de Actividad')),
                ('hours_per_week', models.PositiveIntegerField(default=0, verbose_name='Horas por semana')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Año Académico')),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')], default=1, verbose_name='Semestre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['order', 'faculty', 'subject', 'professor'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación')], max_length=10, verbose_name='Acción')),
                ('changes', models.JSONField(default=dict, verbose_name='Cambios realizados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'verbose_name_plural': 'Historial de Asignaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
