# Generated by Django 6.0.1 on 2026-01-25 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('assignments', '0001_initial'),
        ('professors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.faculty', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='professors.professor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assignments.assignment', verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_changes', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('professor', 'subject', 'faculty', 'assignment_type', 'academic_year', 'semester', 'group')},
        ),
    ]
