# Generated by Django 6.0.1 on 2026-01-25 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['JEFE_DISCIPLINA', 'JEFE_DEPARTAMENTO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines_headed', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Disciplina'),
        ),
        migrations.AddField(
            model_name='subject',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.discipline', verbose_name='Disciplina'),
        ),
    ]
